#! /bin/bash

: ${ZK_CONFIG=$ZK_PATH/conf/zoo.cfg}
: ${ZK_CLIENT_PORT=2181}

echo dataDir=$ZK_DATA >> $ZK_CONFIG
echo clientPort=$ZK_CLIENT_PORT >> $ZK_CONFIG
# Set the cluster id
if [ ! -z "$ZKID" ]; then
    echo $ZKID > $ZK_DATA/myid
fi
# Set the cluster quorum
if [ ! -z "$ZK_QUORUM" ]; then
    IFS=',' read -a quorum <<< "$ZK_QUORUM"
    for member in "${quorum[@]}"; do
        echo "$member" | awk -F'@' '{print "server."$1"="$2}' >> $ZK_CONFIG
    done
fi
# Set additional config
if [ ! -z "$ZK_CONFIG_PARAMS" ]; then
    IFS=',' read -a params <<< "$ZK_CONFIG_PARAMS"
    for member in "${params[@]}"; do
        echo "$member" >> $ZK_CONFIG
    done
fi
# Start zookeeper
$ZK_PATH/bin/zkServer.sh start-foreground
